# Generated by Django 5.0.1 on 2024-02-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskt', '0002_userprofile_floor_handling_userprofile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='floor_handling',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
