# Generated by Django 5.0.1 on 2024-02-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskt', '0003_websitelink_remove_userprofile_floor_handling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmokeDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descp', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('frequency', models.IntegerField()),
            ],
        ),
    ]
